# Download dataset
Brazilian E-commerce Public Dataset (Olist) form Kaggle

<img src="https://i.imgur.com/HRhd2Y0.png" width="1080">

In [1]:
import kagglehub
import os

path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")
print("Path to dataset files:", path)

files = os.listdir(path)
print(files)

Path to dataset files: /Users/kornkanoktripanpitak/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/versions/2
['olist_sellers_dataset.csv', 'product_category_name_translation.csv', 'olist_orders_dataset.csv', 'olist_dataset', 'olist_order_items_dataset.csv', 'olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv']

In [2]:
import pandas as pd

df_orders = pd.read_csv(os.path.join(path, "olist_orders_dataset.csv"))
df_products = pd.read_csv(os.path.join(path, "olist_products_dataset.csv"))
df_products_category = pd.read_csv(os.path.join(path, "product_category_name_translation.csv")) 
df_items = pd.read_csv(os.path.join(path, "olist_order_items_dataset.csv"))
df_sellers = pd.read_csv(os.path.join(path, "olist_sellers_dataset.csv"))
df_customers = pd.read_csv(os.path.join(path, "olist_customers_dataset.csv"))
df_reviews = pd.read_csv(os.path.join(path, "olist_order_reviews_dataset.csv"))
df_payments = pd.read_csv(os.path.join(path, "olist_order_payments_dataset.csv"))
df_locations = pd.read_csv(os.path.join(path, "olist_geolocation_dataset.csv"))

display(df_orders.head(3))
display(df_products.head(3))
display(df_reviews.head(3))
display(df_locations.head(3))

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

In [3]:
import sqlite3
import pandas as pd

# Connect to SQLite (in-memory) to create database
conn = sqlite3.connect(':memory:')

# Convert dataframe to sql table
df_orders.to_sql('orders', conn, index=False, if_exists='replace')
df_products.to_sql('products', conn, index=False, if_exists='replace')
df_products_category.to_sql('products_category', conn, index=False, if_exists='replace')
df_items.to_sql('items', conn, index=False, if_exists='replace')
df_sellers.to_sql('sellers', conn, index=False, if_exists='replace')
df_customers.to_sql('customers', conn, index=False, if_exists='replace')
df_reviews.to_sql('reviews', conn, index=False, if_exists='replace')
df_payments.to_sql('payments', conn, index=False, if_exists='replace')
df_locations.to_sql('locations', conn, index=False, if_exists='replace')

# Query using SQL. read_sql() → executes SQL query
query = "SELECT * FROM orders LIMIT 5;"
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
query = """
SELECT o.order_id, c.customer_city
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
LIMIT 5;
"""
pd.read_sql(query, conn)

                           order_id            customer_city
0  e481f51cbdc54678b7cc49136f2d6af7                sao paulo
1  53cdb2fc8bc7dce0b6741e2150273451                barreiras
2  47770eb9100c2d0c44946d9cf07ec65d               vianopolis
3  949d5b44dbf5de918fe9c16f97b45f8a  sao goncalo do amarante
4  ad21c59c0840e6cb83a9ceb5573f8159              santo andre

# ORDER BY (เรียงข้อมูล)

In [5]:
query = """
SELECT *
FROM orders
ORDER BY order_purchase_timestamp DESC;
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,10a045cdf6a5650c21e9cfeb60384c16,a4b417188addbc05b26b72d5e44837a1,canceled,2018-10-17 17:30:18,None,None,None,2018-10-30 00:00:00
1,b059ee4de278302d550a3035c4cdb740,856336203359aa6a61bf3826f7d84c49,canceled,2018-10-16 20:16:02,None,None,None,2018-11-12 00:00:00
2,a2ac6dad85cf8af5b0afb510a240fe8c,4c2ec60c29d10c34bd49cb88aa85cfc4,canceled,2018-10-03 18:55:29,None,None,None,2018-10-16 00:00:00
3,616fa7d4871b87832197b2a137a115d2,bf6181a85bbb4115736c0a8db1a53be3,canceled,2018-10-01 15:30:09,None,None,None,2018-10-23 00:00:00
4,392ed9afd714e3c74767d0c4d3e3f477,2823ffda607a2316375088e0d00005ec,canceled,2018-09-29 09:13:03,None,None,None,2018-10-15 00:00:00
...,...,...,...,...,...,...,...,...
99436,71303d7e93b399f5bcd537d124c0bcfa,b106b360fe2ef8849fbbd056f777b4d5,canceled,2016-10-02 22:07:52,2016-10-06 15:50:56,None,None,2016-10-25 00:00:00
99437,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00
99438,809a282bbd5dbcabb6f2f724fca862ec,622e13439d6b5a0b486c435618b2679e,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,None,None,2016-09-30 00:00:00
99439,e5fa5a7210941f7d56d0208e4e071d35,683c54fc24d40ee9f8a6fc179fd9856c,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,None,None,2016-10-28 00:00:00
99440,2e7a8482f6fb09756ca50c10d7bfc047,08c5351a6aca1c1589a38f244edeee9d,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,2016-10-18 13:14:51,None,2016-10-20 00:00:00

# GROUP BY (Aggregation ตามกลุ่ม)

In [6]:
query = """
SELECT order_status, COUNT(*) as n
FROM orders
GROUP BY order_status
ORDER BY n DESC
"""

result = pd.read_sql(query, conn)
result

  order_status      n
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

# SELECT + WHERE
```
SELECT column1, column2
FROM table
WHERE condition;
```

In [7]:
query = """
SELECT *
FROM orders
WHERE order_status = 'delivered';
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [8]:
query = """
SELECT *
FROM orders
WHERE order_status IN ('delivered', 'shipped');
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
97580,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
97581,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
97582,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
97583,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
97584,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

# COUNT / SUM / AVG (Aggregation)

In [9]:
query = """
SELECT 
    COUNT(*) AS n,
    AVG(price) AS avg_price,
    SUM(price) AS total_price
FROM items;
"""
pd.read_sql(query, conn)

        n   avg_price  total_price
0  112650  120.653739   13591643.7

# HAVING (filter หลัง aggregation)

In [10]:
query = """
SELECT order_status, COUNT(*) AS n
FROM orders
GROUP BY order_status
HAVING COUNT(*) > 100;
"""
pd.read_sql(query, conn)

  order_status      n
0     canceled    625
1    delivered  96478
2     invoiced    314
3   processing    301
4      shipped   1107
5  unavailable    609

# JOIN

In [11]:
# INNER JOIN
query = """
SELECT o.order_id, c.customer_city
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id;
"""
pd.read_sql(query, conn)

                               order_id            customer_city
0      e481f51cbdc54678b7cc49136f2d6af7                sao paulo
1      53cdb2fc8bc7dce0b6741e2150273451                barreiras
2      47770eb9100c2d0c44946d9cf07ec65d               vianopolis
3      949d5b44dbf5de918fe9c16f97b45f8a  sao goncalo do amarante
4      ad21c59c0840e6cb83a9ceb5573f8159              santo andre
...                                 ...                      ...
99436  9c5dedf39a927c1b2549525ed64a053c      sao jose dos campos
99437  63943bddc261676b46f01ca7ac2f7bd8             praia grande
99438  83c1379a015df1e13d02aae0204711ab              nova vicosa
99439  11c177c8e97725db2631073c19f07b62                  japuiba
99440  66dea50a8b16d9b4dee7af250b4be1a5                     lapa

[99441 rows x 2 columns]

In [12]:
# LEFT JOIN
# Left table = orders. Keeps all orders. Adds customer info if available
# Every row = one order. If customer missing → customer_city = NULL
# Use case: Analyze transactions (order-centric view)
query = """
SELECT o.order_id, c.customer_city
FROM orders o
LEFT JOIN customers c
ON o.customer_id = c.customer_id;
"""
pd.read_sql(query, conn)

                               order_id            customer_city
0      e481f51cbdc54678b7cc49136f2d6af7                sao paulo
1      53cdb2fc8bc7dce0b6741e2150273451                barreiras
2      47770eb9100c2d0c44946d9cf07ec65d               vianopolis
3      949d5b44dbf5de918fe9c16f97b45f8a  sao goncalo do amarante
4      ad21c59c0840e6cb83a9ceb5573f8159              santo andre
...                                 ...                      ...
99436  9c5dedf39a927c1b2549525ed64a053c      sao jose dos campos
99437  63943bddc261676b46f01ca7ac2f7bd8             praia grande
99438  83c1379a015df1e13d02aae0204711ab              nova vicosa
99439  11c177c8e97725db2631073c19f07b62                  japuiba
99440  66dea50a8b16d9b4dee7af250b4be1a5                     lapa

[99441 rows x 2 columns]

In [15]:
# LEFT JOIN
# Left table = customers. Keeps all customers. Adds order info if available
# Every row = one customer (but may repeat if multiple orders). If no order → order_id = NULL
# Use case: Analyze customers (customer-centric view)
query = """
SELECT o.order_id, c.customer_city
FROM customers c
LEFT JOIN orders o
ON o.customer_id = c.customer_id;
"""
pd.read_sql(query, conn)

                               order_id          customer_city
0      00e7ee1b050b8499577073aeb2a297a1                 franca
1      29150127e6685892b6eab3eec79f59c7  sao bernardo do campo
2      b2059ed67ce144a36e2aa97d2c9e9ad2              sao paulo
3      951670f92359f4fe4a63112aa7306eba        mogi das cruzes
4      6b7d50bd145f6fc7f33cebabd7e49d0f               campinas
...                                 ...                    ...
99436  6760e20addcf0121e9d58f2f1ff14298              sao paulo
99437  9ec0c8947d973db4f4e8dcf1fbfa8f1b        taboao da serra
99438  fed4434add09a6f332ea398efd656a5c              fortaleza
99439  e31ec91cea1ecf97797787471f98a8c2                 canoas
99440  28db69209a75e59f20ccbb5c36a20b90                  cotia

[99441 rows x 2 columns]

## SQLite does not support RIGHT JOIN (and also does not support FULL OUTER JOIN)
RIGHT JOIN can be rewritten using LEFT JOIN

In [18]:
# RIGHT JOIN
# มี customer คนไหนที่ ไม่มี order บ้าง
query = """
SELECT c.customer_city, o.order_id
FROM customers c
LEFT JOIN orders o
ON o.customer_id = c.customer_id;
"""
pd.read_sql(query, conn)

               customer_city                          order_id
0                     franca  00e7ee1b050b8499577073aeb2a297a1
1      sao bernardo do campo  29150127e6685892b6eab3eec79f59c7
2                  sao paulo  b2059ed67ce144a36e2aa97d2c9e9ad2
3            mogi das cruzes  951670f92359f4fe4a63112aa7306eba
4                   campinas  6b7d50bd145f6fc7f33cebabd7e49d0f
...                      ...                               ...
99436              sao paulo  6760e20addcf0121e9d58f2f1ff14298
99437        taboao da serra  9ec0c8947d973db4f4e8dcf1fbfa8f1b
99438              fortaleza  fed4434add09a6f332ea398efd656a5c
99439                 canoas  e31ec91cea1ecf97797787471f98a8c2
99440                  cotia  28db69209a75e59f20ccbb5c36a20b90

[99441 rows x 2 columns]

In [17]:
# OUTER JOIN
query = """
SELECT o.order_id, c.customer_id
FROM orders o
LEFT JOIN customers c
ON o.customer_id = c.customer_id

UNION

SELECT o.order_id, c.customer_id
FROM customers c
LEFT JOIN orders o
ON o.customer_id = c.customer_id;
"""
pd.read_sql(query, conn)

                               order_id                       customer_id
0      00010242fe8c5a6d1ba2dd792cb16214  3ce436f183e68e07877b285a838db11a
1      00018f77f2f0320c557190d7a144bdd3  f6dd3ec061db4e3987629fe6b26e5cce
2      000229ec398224ef6ca0657da4fc703e  6489ae5e4333f3693df5ad4372dab6d3
3      00024acbcdf0a6daa1e931b038114c75  d4eb9395c8c0431ee92fce09860c5a06
4      00042b26cf59d7ce69dfabb4e55b4fd9  58dbd0b2d70206bf40e62cd34e84d795
...                                 ...                               ...
99436  fffc94f6ce00a00581880bf54a75a037  b51593916b4b8e0d6f66f2ae24f2673d
99437  fffcd46ef2263f404302a634eb57f7eb  84c5d4fbaf120aae381fad077416eaa0
99438  fffce4705a9662cd70adb13d4a31832d  29309aa813182aaddc9b259e31b870e6
99439  fffe18544ffabc95dfada21779c9644f  b5e6afd5a41800fdf401e0272ca74655
99440  fffe41c64501cc87c801fd61db3f6244  96d649da0cc4ff33bb408b199d4c7dcf

[99441 rows x 2 columns]

In [19]:
# OUTER JOIN
# แบ่งกลุ่ม match vs non-match. มี record ไหนที่ match / ไม่ match ระหว่าง orders กับ customers?
query = """
SELECT 
    CASE 
        WHEN o.order_id IS NOT NULL AND c.customer_id IS NOT NULL THEN 'matched'
        WHEN o.order_id IS NOT NULL THEN 'order_only'
        ELSE 'customer_only'
    END AS status,
    COUNT(*) AS n
FROM orders o
LEFT JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY status;
"""
pd.read_sql(query, conn)

    status      n
0  matched  99441

# CASE WHEN (conditional logic)

In [20]:
query = """
SELECT order_id,
    CASE 
        WHEN price > 100 THEN 'high'
        WHEN price > 50 THEN 'medium'
        ELSE 'low'
    END AS price_level
FROM items;
"""
pd.read_sql(query, conn)

                                order_id price_level
0       00010242fe8c5a6d1ba2dd792cb16214      medium
1       00018f77f2f0320c557190d7a144bdd3        high
2       000229ec398224ef6ca0657da4fc703e        high
3       00024acbcdf0a6daa1e931b038114c75         low
4       00042b26cf59d7ce69dfabb4e55b4fd9        high
...                                  ...         ...
112645  fffc94f6ce00a00581880bf54a75a037        high
112646  fffcd46ef2263f404302a634eb57f7eb        high
112647  fffce4705a9662cd70adb13d4a31832d      medium
112648  fffe18544ffabc95dfada21779c9644f      medium
112649  fffe41c64501cc87c801fd61db3f6244         low

[112650 rows x 2 columns]

# DATE / TIME

In [21]:
# ดึงปี / เดือน
query = """
SELECT 
    strftime('%Y', order_purchase_timestamp) AS year,
    COUNT(*) AS n
FROM orders
GROUP BY year;
"""
pd.read_sql(query, conn)

   year      n
0  2016    329
1  2017  45101
2  2018  54011

In [22]:
# Filter วันที่
query = """
SELECT *
FROM orders
WHERE date(order_purchase_timestamp) >= '2018-01-01';
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
1,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
3,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
4,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
...,...,...,...,...,...,...,...,...
54006,c22a47117b6a87c967b0c278488110c1,6e153567dc52ea59c0498ef5383e9c7a,delivered,2018-06-22 20:53:29,2018-06-22 21:17:45,2018-06-25 17:50:00,2018-07-03 19:48:54,2018-07-23 00:00:00
54007,c81f74e50f0496fa39716cc77cacd460,7b270ebc87c25c8404348c10ff80a80e,delivered,2018-03-04 22:48:38,2018-03-04 23:09:22,2018-03-05 16:15:04,2018-03-13 18:54:32,2018-03-26 00:00:00
54008,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
54009,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
54010,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [29]:
# filter orders in the AM (morning hours) between 2017-2019
query = """
SELECT *
FROM orders
WHERE strftime('%Y', order_purchase_timestamp) BETWEEN '2017' AND '2019' 
  AND CAST(strftime('%H', order_purchase_timestamp) AS INTEGER) < 12;
"""
pd.read_sql(query, conn)

# WHERE strftime('%Y', order_purchase_timestamp) BETWEEN '2017' AND '2019' = 
# WHERE order_purchase_timestamp >= '2017-01-01' AND order_purchase_timestamp < '2019-01-01'

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
2,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
3,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
4,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00
...,...,...,...,...,...,...,...,...
26875,7cc85185736ea7f2d8bc09af7a47cab7,9e870ea67399650e8c3545a25d13e4d0,delivered,2017-05-15 09:46:26,2017-05-15 10:02:45,2017-05-15 14:11:06,2017-05-22 18:05:56,2017-06-07 00:00:00
26876,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18 00:00:00
26877,aa04ef5214580b06b10e2a378300db44,f01a6bfcc730456317e4081fe0c9940e,delivered,2017-01-27 00:30:03,2017-01-27 01:05:25,2017-01-30 11:40:16,2017-02-07 13:15:25,2017-03-17 00:00:00
26878,880675dff2150932f1601e1c07eadeeb,47cd45a6ac7b9fb16537df2ccffeb5ac,delivered,2017-02-23 09:05:12,2017-02-23 09:15:11,2017-03-01 10:22:52,2017-03-06 11:08:08,2017-03-22 00:00:00
26879,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00

In [31]:
query = """
SELECT COUNT(*) AS n_am_orders
FROM orders
WHERE order_purchase_timestamp >= '2017-01-01'
  AND order_purchase_timestamp < '2019-01-01'
  AND CAST(strftime('%H', order_purchase_timestamp) AS INTEGER) < 12;
"""
pd.read_sql(query, conn)

   n_am_orders
0        26880

# DISTINCT (unique values)

In [32]:
query = """
SELECT DISTINCT customer_city
FROM customers;
"""
pd.read_sql(query, conn)

              customer_city
0                    franca
1     sao bernardo do campo
2                 sao paulo
3           mogi das cruzes
4                  campinas
...                     ...
4114                 siriji
4115    natividade da serra
4116           monte bonito
4117             sao rafael
4118      eugenio de castro

[4119 rows x 1 columns]

# Subquery

In [34]:
# Inner query (subquery) = Returns all customer_id values for customers located in sao paulo
# Outer query = Selects all orders where the customer_id matches any ID from that list
query = """
SELECT *
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM customers
    WHERE customer_city = 'sao paulo'
);
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00
2,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
3,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00
4,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00
...,...,...,...,...,...,...,...,...
15535,c2af225ac9a68a3c24500aa6fab006aa,f93c9e539a9705a57902c625b611e90c,delivered,2018-08-20 10:04:30,2018-08-20 14:53:46,2018-08-22 13:16:00,2018-08-27 21:44:45,2018-08-28 00:00:00
15536,87b4c933f31145a28413b39d880ad6c3,ddfdf5e9b2659e1fbd073404c9b762e0,delivered,2018-03-02 17:12:05,2018-03-02 17:49:24,2018-03-06 21:23:32,2018-03-16 17:21:55,2018-03-21 00:00:00
15537,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,delivered,2017-08-10 21:21:07,2017-08-10 21:35:26,2017-08-18 16:42:51,2017-08-23 15:36:29,2017-08-31 00:00:00
15538,0e4b26f1fb99fc0f0472dd5f403d36d4,2e96fa6d55b9732013caed9866e2552d,delivered,2017-11-05 16:17:53,2017-11-05 16:30:29,2017-11-07 18:35:08,2017-11-08 16:08:56,2017-11-17 00:00:00
15539,880675dff2150932f1601e1c07eadeeb,47cd45a6ac7b9fb16537df2ccffeb5ac,delivered,2017-02-23 09:05:12,2017-02-23 09:15:11,2017-03-01 10:22:52,2017-03-06 11:08:08,2017-03-22 00:00:00

In [38]:
# Above subquery equivalent to this JOIN
query = """
SELECT o.*
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
WHERE c.customer_city = 'sao paulo';
"""
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,b2059ed67ce144a36e2aa97d2c9e9ad2,4e7b3e00288586ebd08712fdd0374a03,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
1,36e694cf4cbc2a4803200c35e84abdc4,fd826e7cf63160e536e0908c76c3f441,delivered,2018-02-19 14:38:35,2018-02-19 14:50:37,2018-02-20 00:03:39,2018-02-20 16:25:51,2018-03-05 00:00:00
2,852d2f4d37773bcbc21c8e09a05a4ea5,eabebad39a88bb6f5b52376faec28612,delivered,2018-03-07 15:57:14,2018-03-07 16:15:30,2018-03-12 23:02:49,2018-03-15 00:46:30,2018-03-19 00:00:00
3,17825f24877a9289214c301ae0c9424b,9b8ce803689b3562defaad4613ef426f,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,2017-06-07 12:02:14,2017-05-30 00:00:00
4,0198c71148c2e08c7c52b860f640fa4e,2938121a40a20953c43caa8c98787fcb,delivered,2018-05-08 06:34:07,2018-05-09 04:31:29,2018-05-10 18:12:00,2018-05-18 18:49:30,2018-05-29 00:00:00
...,...,...,...,...,...,...,...,...
15535,b2f58affcc178fea2daaf834f1acff5e,f6c6d3e1e20969a5eed982163f959719,delivered,2018-07-14 14:08:11,2018-07-17 04:31:33,2018-07-25 11:18:00,2018-07-26 19:18:32,2018-07-30 00:00:00
15536,c8203bb57639618630affac9e8e923dd,da37711b17efd5f2539e8196ab215f04,delivered,2017-03-27 23:04:18,2017-03-27 23:23:38,2017-03-28 14:18:59,2017-03-30 17:06:19,2017-04-13 00:00:00
15537,49645a8902c1ba980836b7bff991d69f,821a7275a08f32975caceff2e08ea262,delivered,2018-04-04 17:50:52,2018-04-04 18:08:41,2018-04-05 16:36:49,2018-04-06 23:32:21,2018-04-18 00:00:00
15538,52b783557d95971d0b42195e6bacdc68,c6ece8a5137f3c9c3a3a12302a19a2ac,delivered,2017-10-20 07:16:27,2017-10-20 07:28:14,2017-10-23 19:13:38,2017-10-24 17:03:38,2017-11-01 00:00:00
15539,6760e20addcf0121e9d58f2f1ff14298,17ddf5dd5d51696bb3d7c6291687be6f,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00

# Window Functions

In [36]:
query = """
SELECT 
    order_id,
    price,
    AVG(price) OVER () AS global_avg
FROM items;
"""
pd.read_sql(query, conn)

                                order_id   price  global_avg
0       00010242fe8c5a6d1ba2dd792cb16214   58.90  120.653739
1       00018f77f2f0320c557190d7a144bdd3  239.90  120.653739
2       000229ec398224ef6ca0657da4fc703e  199.00  120.653739
3       00024acbcdf0a6daa1e931b038114c75   12.99  120.653739
4       00042b26cf59d7ce69dfabb4e55b4fd9  199.90  120.653739
...                                  ...     ...         ...
112645  fffc94f6ce00a00581880bf54a75a037  299.99  120.653739
112646  fffcd46ef2263f404302a634eb57f7eb  350.00  120.653739
112647  fffce4705a9662cd70adb13d4a31832d   99.90  120.653739
112648  fffe18544ffabc95dfada21779c9644f   55.99  120.653739
112649  fffe41c64501cc87c801fd61db3f6244   43.00  120.653739

[112650 rows x 3 columns]

In [37]:
# Ranking
query = """
SELECT 
    order_id,
    price,
    RANK() OVER (ORDER BY price DESC) AS rank_price
FROM items;
"""
pd.read_sql(query, conn)

                                order_id    price  rank_price
0       0812eb902a67711a1cb742b3cdaa65ae  6735.00           1
1       fefacc66af859508bf1a7934eab1e97f  6729.00           2
2       f5136e38d1a14a4dbd87dff67da82701  6499.00           3
3       a96610ab360d42a2e5335a3998b4718a  4799.00           4
4       199af31afc78c699f0dbf71fb178d4d4  4690.00           5
...                                  ...      ...         ...
112645  8272b63d03f5f79c56e9e4120aec44ef     1.20      112628
112646  8272b63d03f5f79c56e9e4120aec44ef     1.20      112628
112647  3ee6513ae7ea23bdfab5b9ab60bffcb5     0.85      112648
112648  6e864b3f0ec71031117ad4cf46b7f2a1     0.85      112648
112649  c5bdd8ef3c0ec420232e668302179113     0.85      112648

[112650 rows x 3 columns]

# Full example #1
To identify high-activity cities and classify them into high-value vs low-value segments based on average purchase price.

In [53]:
query = """
SELECT 
    c.customer_city,
    COUNT(o.order_id) AS n_orders,
    AVG(i.price) AS avg_price,
    CASE 
        WHEN AVG(i.price) > 100 THEN 'high_value'
        ELSE 'low_value'
    END AS segment
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN items i ON o.order_id = i.order_id
GROUP BY c.customer_city
HAVING n_orders > 50
ORDER BY avg_price DESC;
"""
result1 = pd.read_sql(query, conn)
display(result1)

# result1.to_csv("city_purchase_segmentation.csv", index=False)

            customer_city  n_orders   avg_price     segment
0            porto seguro        51  252.746863  high_value
1          campina grande        75  233.340400  high_value
2             divinopolis       164  215.254695  high_value
3               petrolina        69  207.434783  high_value
4               nova lima       104  201.558173  high_value
..                    ...       ...         ...         ...
288               cubatao        87   80.414138   low_value
289  itapecerica da serra       109   80.172294   low_value
290               vinhedo       115   79.590174   low_value
291                viamao        85   78.295294   low_value
292             araucaria        65   78.247692   low_value

[293 rows x 4 columns]

# Full Example #2
Identify products (“menu”) ordered in AM (morning) during 2017–2019, and compute: 
- total revenue
- number of orders

In [52]:
query = """
SELECT 
    p.product_category_name AS menu,
    COUNT(DISTINCT o.order_id) AS n_orders,
    SUM(i.price) AS revenue
FROM orders o
JOIN items i 
    ON o.order_id = i.order_id
JOIN products p 
    ON i.product_id = p.product_id
JOIN products_category pc
    ON p.product_category_name = pc.product_category_name_english
WHERE o.order_purchase_timestamp >= '2017-01-01'
  AND o.order_purchase_timestamp < '2018-01-01'
  AND CAST(strftime('%H', o.order_purchase_timestamp) AS INTEGER) < 12
GROUP BY pc.product_category_name_english
ORDER BY revenue DESC;
"""
result2 = pd.read_sql(query, conn)
display(result2)

# result2.to_csv("AMorders.csv", index=False)

             menu  n_orders    revenue
0      cool_stuff       576  108190.96
1        pet_shop       188   22400.78
2  consoles_games       191   22130.32
3           audio        53    5551.26
4    market_place        48    4780.97
5    dvds_blu_ray        12    2031.90
6      la_cuisine         3     395.99